### ISSUE TITLE
connect() got multiple values for argument 'ip_type' 

### ISSUE THREAD

**Issue by mikepietruszka** [GoogleCloudPlatform/cloud-sql-python-connector#244]
## Bug Description

Hello, I'm getting below error when using `ip_type` flag in `connector.connect()` function call. I am trying to access my Cloud SQL instance using a private IP address.

## Example code (or command)

```python
from google.cloud.sql.connector import connector, instance_connection_manager

def init_connection_engine(db_instance, db_user, db_pass, db_name) -> sqlalchemy.engine.Engine:
    '''
    Utility function: Database pooling/connection init
    '''
    def getconn() -> pg8000.dbapi.Connection:
        conn: pg8000.dbapi.Connection = connector.connect(
            db_instance,
            "pg8000",
            ip_type=instance_connection_manager.IPTypes.PRIVATE,
            user=db_user,
            password=db_pass,
            db=db_name,
        )
        return conn

    engine = sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator=getconn,
    )
    engine.dialect.description_encoding = None
    return engine
```

## Stacktrace
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 231, in process_message
    with pool.connect() as db_conn:
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 241, in <lambda>
    return lambda crec: creator()
  File "/workspace/main.py", line 53, in getconn
    conn: pg8000.dbapi.Connection = connector.connect(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/sql/connector/connector.py", line 123, in connect
    raise (e)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/cloud/sql/connector/connector.py", line 119, in connect
    return icm.connect(driver, ip_types, timeout, **kwargs)
TypeError: connect() got multiple values for argument 'ip_type'
```

## How to reproduce

  1. Call connector.connect with appropriate arguments, preferably within a VPC as we're trying to access the Cloud SQL instance using a private IP address.

## Environment

1. OS type and version: Cloud Functions
2. Python version: python3.9
2. Connector version: `cloud-sql-python-connector[pg8000]==0.4.1` (I'm using 0.4.1 because of https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/240).

**Comment by mikepietruszka** [comment]
This seems like an issue in 0.4.1:
```
$ pip show cloud-sql-python-connector | grep Version
Version: 0.4.1
$ python test.py
Engine: Engine(postgresql+pg8000://)
Traceback (most recent call last):
  File "/home/username/code/github.com/gcp-cloudsql/test.py", line 57, in <module>
    with pool.connect() as db_conn:
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 241, in <lambda>
    return lambda crec: creator()
  File "/home/username/code/github.com/gcp-cloudsql/test.py", line 28, in getconn
    conn: pg8000.dbapi.Connection = connector.connect(
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/google/cloud/sql/connector/connector.py", line 123, in connect
    raise (e)
  File "/home/username/code/github.com/gcp-cloudsql/lib/python3.9/site-packages/google/cloud/sql/connector/connector.py", line 119, in connect
    return icm.connect(driver, ip_types, timeout, **kwargs)
TypeError: connect() got multiple values for argument 'ip_type'
```

Appears to work in 0.5.0:
```
$ pip show cloud-sql-python-connector | grep Version
Version: 0.5.0
$ python test.py
Engine: Engine(postgresql+pg8000://)
2022-01-14 17:43:02,223 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-01-14 17:43:02,224 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-01-14 17:43:02,228 INFO sqlalchemy.engine.Engine select current_schema()
2022-01-14 17:43:02,228 INFO sqlalchemy.engine.Engine [raw sql] ()
2022-01-14 17:43:02,231 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-01-14 17:43:02,231 INFO sqlalchemy.engine.Engine [raw sql] ()
```

I suppose this can be closed since it's fixed in 0.5.0 :)

**Comment by jackwotherspoon** [comment]
Hi @mikepietruszka, in 0.5.0 we introduced the new flag `ip_type` to eventually replace the old flag `ip_types` to better describe it and be more clear. The documentation reflects the latest version and best practice we want people to use going forward.

Therefore, if you are using an older version, the flag `ip_types` instead of `ip_type` should allow everything to run smoothly.

Hope this helps clear it up. Thanks for the feedback :)

**Comment by mikepietruszka** [comment]
Thank you @jackwotherspoon, that makes total sense!
