### ISSUE TITLE
pg8000 Postgres - struct.error: 'h' format requires -32768 <= number <= 32767

### ISSUE THREAD

**Issue by KitHaywood** [GoogleCloudPlatform/cloud-sql-python-connector#328]
## Bug Description

I am trying to write a large pandas dataframe (3,000,000 x 8) to a GCP hosted Postgres database. I am using something similar to the following to write my data.

## Example code (or command)

```python
rom sqlalchemy import Table,MetaData,Column,String,Integer,Float,DateTime,ARRAY,BigInteger
import pandas as pd
import sqlalchemy
from datetime import datetime
from google.cloud.sql.connector import connector
import numpy as np
import random

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "path-to-your-keys"
Base = declarative_base()

os.environ['DB_USER'] = "root-user"
os.environ['DB_PROJECTID']  ="project-id-from-GCP"
os.environ["DB_NAME"] = "DB-NAME"
os.environ["DB_PASS"] = "your-password-for-the-GCP-DB"

def getconn():
    conn = connector.connect(
        os.environ["DB_PROJECTID"],
        "pg8000",
        user=os.environ["DB_USER"],
        password=os.environ["DB_PASS"],
        db=os.environ["DB_NAME"],
    )
    return conn

db = sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator=getconn,
    )

def make_dummy_df():
    rng = np.random.default_rng()
    df = pd.DataFrame(rng.integers(0, 50000, size=(3000000, 1)), columns=['window'])
    df['start'] = list(pd.date_range(start=datetime(2020,1,1),end=datetime.today(),periods=int(df.shape[0])))
    df['end'] = list(pd.date_range(start=datetime(2020,1,1),end=datetime.today(),periods=int(df.shape[0])))
    df['degree'] = [random.randint(0,40) for _ in range(df.shape[0])]
    df['x'] = [random.sample(range(10000, 100000), 10) for _ in range(df.shape[0])]
    df['y'] = [random.sample(range(-100, 100), 10) for _ in range(df.shape[0])]
    df['z'] = [random.sample(range(100, 1000), 10) for _ in range(df.shape[0])]      
    df['index'] = df.index                  
    return df

if __name__=="__main__":
    df = make_dummy_df()
    df.to_sql(
        "test1",
        con=db,
        if_exists="replace",
        index=False,
        method="multi",
        chunksize=10000,
        dtype={
             "index":BigInteger(),
             "window":Integer(),
             "degree":Integer(),
             "start":DateTime(),
             "end":DateTime(),
             "x":ARRAY(Float),
             "y":ARRAY(Float),
             "z":ARRAY(Float)
         })
```
Raises the following error when run in a Linux Environment. The linux machine is a Virtual Machine on AWS EC2 Ubuntu Server 20.04 LTS (HVM), SSD Volume Type c4.8xlarge
## Stacktrace
```
Traceback (most recent call last):                                                                                                                       
  File "testing.py", line 53, in <module>                                                                               
    df.to_sql(                                                                                                                       
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2963, in to_sql                     
    return sql.to_sql(                                                         
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 697, in to_sql                          
    return pandas_sql.to_sql(                                                  
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1739, in to_sql                         
    total_inserted = sql_engine.insert_records(                                
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1322, in insert_records           
    return table.insert(chunksize=chunksize, method=method)                    
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 950, in insert 
    num_inserted = exec_insert(conn, keys, chunk_iter)                                                                       
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 873, in _execute_insert_multi        
    result = conn.execute(stmt)                                                                                                                       
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1295, in execute        
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)                                                                               
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection       
    return connection._execute_clauseelement(                                                                               
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1487, in _execute_clauseelement       
    ret = self._execute_context(                                                                                                                       
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1851, in _execute_context       
    self._handle_dbapi_exception(                                                                                                                       
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2036, in _handle_dbapi_exception       
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pg8000/dbapi.py", line 455, in execute
    self._context = self._c.execute_unnamed(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pg8000/core.py", line 627, in execute_unnamed
    self.send_PARSE(NULL_BYTE, statement, oids)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pg8000/core.py", line 601, in send_PARSE
    val.extend(h_pack(len(oids)))
struct.error: 'h' format requires -32768 <= number <= 32767
```

## How to reproduce

  1. Setup a Postgres 13 Database in GCP - withdraw all authentification keys etc
  3. Setup a EC2 instance and grab the code above
  4. install python3
  5. pip3 install the dependencies
  6. Run the code above on the EC2 instance. 

## Environment

1. OS type and version: Linux ip-xxx-xx-xx-xx A.B.C-D-aws -Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linu
2. Python version: `python --version`
2. Connector version: <YOUR_VERSION_HERE> 

```
Numpy:                        1.22.3
Pandas:                       1.4.1
SqlAlchemy:                   1.4.32
cloud-sql-python-connector:   0.5.2
```

**Comment by jackwotherspoon** [comment]
Hi @KitHaywood, I've taken some time to look into this issue a little further! Thanks for your patience.

I was able to replicate the issue and play around with the code sample you gave. My takeaway is that this is most likely an issue with the database driver [pg8000](https://github.com/tlocke/pg8000) as that is where all the errors stem from when running a stacktrace. The driver starts seeing errors when writing extremely large quantities of data at once using `df.to_sql`.

The SQLAlchemy Engine for the pg8000 driver seems to start complaining with the error when writing large dataframes to the database (I seem to see the error with dataframes that have more than 5000 rows).

However, I was able to get your sample to work for a (3,000,000 x 8) dataframe by having the `chunksize=4000` within the call to `df.to_sql`. It seems as though if you stay under the 5000 rows at once threshold you can manage to have it work without issues. 

I apologize for this inconvenience and if changing the `chunksize` doesn't fit your needs then I would recommend raising an issue on the [pg8000](https://github.com/tlocke/pg8000) repo directly to have someone take a look at this.

We are currently working to add support for more database driver options. Hopefully this will give some more flexibility and options in the future.

Thanks again for raising this issue and bringing it to our attention.

**Comment by KitHaywood** [comment]
Hi Jack, 

The write is a means to an end, and I won't be hitting a performance constraint by chunking it up. Interestingly - I got round the problem in the meantime by creating a bulk-insert statement from the db cursor directly. Guess what - I'm writing them in chunks of .... 4000. I had hoped that minds brighter than mine might see something I haven't - turns out we're all building on the same slightly unstable driver. What can you do? I'm certainly not building a replacement!

Your module is UNBELEIVABLY helpful so cheers and happy coding!

Kit

**Comment by jackwotherspoon** [comment]
Glad to hear you got around the problem! I will close this issue for now. Feel free to raise any other issues if need be.

Thanks and have a great day!
