### ISSUE TITLE
Crushing after pyOpenSSL release

### ISSUE THREAD

**Issue by IlyaKalosha1** [GoogleCloudPlatform/cloud-sql-python-connector#484]
## Bug Description
After pyOpenSSL was released to 22.1.0 the error become raising

## Stacktrace

Traceback (most recent call last): File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module> sys.exit(_cli()) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/_cli.py", line 37, in _cli app = create_app(target, source, signature_type) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 237, in create_app spec.loader.exec_module(source_module) File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/workspace/main.py", line 3, in <module> from config import CONFIG File "/workspace/config.py", line 4, in <module> from google.cloud.sql.connector import connector File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/sql/connector/__init__.py", line 19, in <module> from .connector import connect File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/sql/connector/connector.py", line 19, in <module> from google.cloud.sql.connector.instance_connection_manager import ( File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/sql/connector/instance_connection_manager.py", line 32, in <module> import OpenSSL File "/layers/google.python.pip/pip/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module> from OpenSSL import SSL, crypto File "/layers/google.python.pip/pip/lib/python3.7/site-packages/OpenSSL/SSL.py", line 19, in <module> from OpenSSL.crypto import ( File "/layers/google.python.pip/pip/lib/python3.7/site-packages/OpenSSL/crypto.py", line 3232, in <module> name="load_pkcs7_data", TypeError: deprecated() got an unexpected keyword argument 'name'

## How to reproduce

 1.  install requirements without fixed version for pyOpenSSL
 2. call "from google.cloud.sql.connector import connector"
 

## Environment

1. OS type and version: linux(google cloud functions)
2. Python version: 3.7.5
2. Connector version:  cloud-sql-python-connector==0.5.2

**Comment by jackwotherspoon** [comment]
Hi @IlyaKalosha1, thanks for raising a bug on the Cloud SQL Python Connector!

It looks like you are using an older version of the Python Connector (0.5.2), as of the latest version (0.8.1) PyOpenSSL has been dropped as a core dependency from the Python Connector #423.

Updating your application to use the latest version of the Python Connector should resolve the error and would be the recommended solution. 

Alternatively, if you don't want to update to the latest version of the Python Connector and keep your code as is in the meantime, you can pin the `pyOpenSSL` dependency in your application to an older version. 

Since you are using Cloud Functions, you would just add `pyOpenSSL==22.0.0` to your `requirements.txt` file.

Let me know if either of these approaches helps resolve your error!

I'll also look at adding version constraints to our [`setup.py`](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/setup.py#L45-L50) so this type of error doesn't occur in the future. 

Thanks for raising this and have a great day 😄

**Comment by IlyaKalosha1** [comment]
Thank you
We've already solved it using pyOpenSSL==22.0.0 in requirements.txt file.  And
I think will migrate to the newer version of python connector soon.
