### ISSUE TITLE
enable_iam_auth not working for mysql connections

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/cloud-sql-python-connector#499]
## Bug Description

I can use enable_iam_auth with postgres but not mysql

## Example code (or command)

```python
    def getconn() -> pymysql.connections.Connection:
        conn: pymysql.connections.Connection = connector.connect(
            "myproject:us-central1:mydb",
            "pymysql",
            user="mygsa", # full email is mygsa@myproject.iam.gserviceaccount.com
            db="mydb",
            enable_iam_auth=True,
        )
        return conn
```

## Stacktrace
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 245, in <lambda>
    return lambda crec: creator()
  File "/app/src/connect_to_mysql.py", line 53, in getconn
    conn: pymysql.connections.Connection = connector.connect(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 146, in connect
    return connect_task.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 245, in connect_async
    raise (e)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 239, in connect_async
    return await asyncio.wait_for(get_connection(), timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 235, in get_connection
    return await self._loop.run_in_executor(None, connect_partial)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/pymysql.py", line 57, in connect
    conn.connect(sock)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1043, 'Bad handshake')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/./src/myapp.py", line 99, in <module>
    metric_value = get_metric(conn, db_qry)
  File "/app/./src/myapp.py", line 40, in get_metric
    with pool.connect() as db_conn:
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 320, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
    self.__connect()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    with util.safe_reraise():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 245, in <lambda>
    return lambda crec: creator()
  File "/app/src/connect_to_mysql.py", line 53, in getconn
    conn: pymysql.connections.Connection = connector.connect(
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 146, in connect
    return connect_task.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 245, in connect_async
    raise (e)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 239, in connect_async
    return await asyncio.wait_for(get_connection(), timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/connector.py", line 235, in get_connection
    return await self._loop.run_in_executor(None, connect_partial)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/sql/connector/pymysql.py", line 57, in connect
    conn.connect(sock)
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1043, 'Bad handshake')
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

## How to reproduce

Try to use enable_iam_auth with a mysql connection

## Environment
cloud-sql-python-connector==0.8.1
macos

**Comment by kurtisvg** [comment]
Hey @red8888,

Thanks for taking the time to open an issue. Automatic IAM DB AuthN is not supported for MySQL or SQL server. There's a PR WIP (https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/466), and we started throwing an error (https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/476) to better indicate that to users. When the first PR get's merged + release, Auto IAM DB AuthN will be working.

**Comment by red8888** [comment]
Thanks for the quick response. Do you know what the ETA is? I know they only just started supporting this for MySQL. 

I didn't get any emails or see blog posts announcing it from google only just stumbled on it today. It's weird how under the radar this feature was rolled out. There is also a bug related to this the terraform provider :/

**Comment by kurtisvg** [comment]
@red8888 Unfortunately it's under the radar because it's not actually released yet. You can see the [MySQL page doesn't mention "Automatic IAM DB AuthN"](https://cloud.google.com/sql/docs/mysql/authentication#options), while [Postgres does](https://cloud.google.com/sql/docs/postgres/authentication#automatic).

**Comment by kurtisvg** [comment]
Unfortunately I can't speak for the ETA, but if you keep an eye on #466 is should be available shortly after it becomes merged.
