### ISSUE TITLE
Brief summary of your question

### ISSUE THREAD

**Issue by pfitzsi1** [GoogleCloudPlatform/cloud-sql-python-connector#764]
### Question

Hi!  Not sure if this is a bug or if I'm missing something.
Having trouble trying to use the cloud-sql-python-connector within a Google Function trying to connect to our Postgres DB via VPC Serverless Connector.

Coding follows https://github.com/GoogleCloudPlatform/cloud-sql-python-connector
It is getting stuck trying to get an ephemeral certificate and timing out.
I've increased the timeout specified up to 180 seconds but still timing out.
I've tried with most recent versions of the connector (1.2.4) and python 311 and also with the older versions specified here (1.2.3 and python 310).

Log message where it gets stuck until times out:
   _get_ephemeral @ line 162 - ['svcqual-cld']: Requesting ephemeral certificate    (line 160 for python 310)

If python 310, then:
   _refresh_task @ line 390 - ['cdo-service-qual-np-b56cfb:northamerica-northeast1:svcqual-cld']: Schedule refresh task cancelled.

If python 311, then:
   _perform_refresh @ line 350 - ['cdo-service-qual-np-b56cfb:northamerica-northeast1:svcqual-cld']: Error occurred during _perform_refresh.

Using a service account and WIF.
Have tons of roles added to both the service account and the Google Functions (robot) service account.
I've tried adding all kinds of roles to both, including roles/owner.

For testing have tried both Google Console (passes in the IAM Bearer token) and gcloud where passing the IAM token via --access-token-file= where the token was obtained immediately before the call.

Not sure why it is even trying to obtain an ephemeral certificate.

**Comment by jackwotherspoon** [comment]
@pfitzsi1 Thanks for raising an issue 😄 

Do you mind pasting the application code for your Google Cloud Function below?

Will help in debugging this, thanks!

**Comment by pfitzsi1** [comment]
OK, here is the connector function:

import os
import time
import pg8000
import flask
import sqlalchemy
import logging
from google.cloud.sql.connector import Connector, IPTypes
import deprecation

def connectWithConnector() -> sqlalchemy.engine.base.Engine:

    start_time = time.time()

    # Setup Variables
    project_id              = os.environ["project_id"]
    project_number          = os.environ["project_number"]
    region                  = os.environ["region"]
    db_instance             = os.environ["db_instance"]
    db_host                 = os.environ["db_host"]        # Not used
    db_port                 = os.environ["db_port"]        # Not used
    db_name                 = os.environ["db_name"]
    db_user                 = os.environ["db_user"]
    db_tmfsq_batch_password = os.environ["db_tmfsq_batch_password"] # Gets this from Google Secrets
    db_driver_name          = "postgresql+pg8000"
    db_connection_name      = project_id + ":" + region + ":" + db_instance
    db_ip_type              = IPTypes.PRIVATE

    def getConn() -> pg8000.dbapi.Connection:

        sub_start_time = time.time()

        try:

            logging.info(f"Attempting to create a Database Connection for user <{db_user}> to database <{db_name}>...")
            with Connector() as connector:
                conn = connector.connect(
                    db_connection_name,
                    "pg8000",
                    user=db_user,
                    password=db_tmfsq_batch_password,
                    db=db_name,
                    ip_type=db_ip_type,
                    timeout=180
                ) 

        except Exception as err:

            logging.exception(f"Database Connection failed with error: <{err}>")
            sub_elapsed_time = round(time.time() - sub_start_time, 2)
            logging.info(f"Elapsed Time for getConn = <{sub_elapsed_time}> seconds")
            raise

        else:

            logging.info(f"Database Connection established for user <{db_user}> to database <{db_name}>")   
            sub_elapsed_time = round(time.time() - sub_start_time, 2)
            logging.info(f"Elapsed Time for getConn = <{sub_elapsed_time}> seconds")
            return conn

    # Create a Database Connection Pool
    # Cloud SQL Python Connector can be used with SQLAlchemy using the 'creator' argument to 'create_engine'
    try:

        logging.info(f"Attempting to create a Database Connection Pool...")
        pool = sqlalchemy.create_engine(
            db_driver_name + "://",
            creator=getConn(),
            pool_size=5,               # Maximum number of permanent connections to keep.
            max_overflow=2,            # Temporarily exceeds the set pool_size if no connections are available.
            pool_timeout=240,          # Maximum number of seconds to wait for a new connection from the pool.
            pool_recycle=1800          # Maximum number of seconds a connection can persist.
        )

    except Exception as err:

        logging.exception(f"Database Connection Pool failed with error: <{err}>")
        elapsed_time = round(time.time() - start_time, 2)
        logging.info(f"Elapsed Time for connectWithConnector = <{elapsed_time}> seconds")
        raise

    else:

        logging.info(f"Database Connection Pool established")
        elapsed_time = round(time.time() - start_time, 2)
        logging.info(f"Elapsed Time for connectWithConnector = <{elapsed_time}> seconds")
        return pool

**Comment by pfitzsi1** [comment]
In requirements.txt right now I have:

google-cloud-core==2.3.2
google-api-python-client==2.88.0
functions-framework==3.3.0

cloud-sql-python-connector==1.2.3
deprecation==2.1.0
Flask==2.3.2
pg8000==1.29.6
protobuf==4.23.2
SQLAlchemy==2.0.15
gunicorn==20.1.0

**Comment by pfitzsi1** [comment]
Note that I used a Context Manager (with) so that connection closing would be auto handled, (was getting open connection warnings / errors when testing before I changed it to use with).

**Comment by jackwotherspoon** [comment]
@pfitzsi1 I thought of one thing you may want to try but first I'll give a little background on how the connector works.

> Not sure why it is even trying to obtain an ephemeral certificate.

The Cloud SQL Python Connector creates an ephemeral TLS certificate and retrieves the instance’s IP addresses by calling [Cloud SQL Admin APIs](https://cloud.google.com/sql/docs/mysql/admin-api). It does this in order to create a secure TLS/SSL connection to your Cloud SQL instance. 

The Cloud SQL Admin API calls are over HTTPS, so egress connections on port 443 must be allowed by your VPC network. I believe this may be the cause of your errors. Check that your VPC network does not have a firewall rule blocking egress HTTPS connections over port 443 or try adding a firewall rule to allow them.

Let me know if this works, if it does not I can dive deeper into trying to resolve this.

**Comment by jackwotherspoon** [comment]
An easier potential solution to try would be to edit your Cloud Function under "Connections -> Egress settings" and make sure to only route requests to private IPs through the VPC Connector, this way the Cloud SQL Admin API calls will still be over public IP and not cause the error:

![image](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/assets/32113413/c16fa70f-ebcc-4d83-a02f-abc23d63991d)

**Comment by pfitzsi1** [comment]
Let me check...

**Comment by pfitzsi1** [comment]
It is already set to Route only requests to private IPs through the VPC connector.

Will check the firewall rules.

**Comment by jackwotherspoon** [comment]
We have seen several timeout issues come up across our Proxy and Connector libraries over the past few days. This hints at the potential of a server side bug on the Cloud SQL server. 

Linking as potentially related: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1840

**Comment by janzawadzkiaml** [comment]
Having the same issue - it's **sporadic**, system is fine for periods of time, then these happen on every connection for a few minutes.  It's a P1 for us.

**Comment by jackwotherspoon** [comment]
@jcz-aml Thanks for letting us know, will bump the priority up on this as it seems to be prevalent.

@jcz-aml Are you able to provide a stacktrace of the errors you are seeing? Also are you able to provide a bit of detail on your usage so I can try and see about reproducing this. 

1) Are you using a Public or Private IP Cloud SQL connection?
2) What environment are you using the Cloud SQL Python Connector with? (Local machine, Cloud Run, App Engine etc.)
3) Are you using standard user and password authentication to login or Automatic IAM database authentication?

Let me know as these details will be very helpful as I try and reproduce this.

**Comment by cw-optima-ovo** [comment]
Also seeing this sporadically regardless to whether the sql connector is configured for public or private IP connections.

I'm using the connector in this context on a cloud run configuration within FastAPI. It works fine under lower levels of load but as soon as I ramp up load testing (using locust) to a max of 100 requests concurrently over 30s I start to see this error a lot more.

Cloud run instance is currently configured to have a cold start but even with a warm start (min instance of 1) it's still a problem. Max instances is 100 and max instance concurrency is 50, cpu and memory are barely getting scratches (4 vcpu 8GB ram configuration).

From uvicorn's local output I get this error:
```
task: <Task pending name='Task-20' coro=<_get_ephemeral() running at /home/cloudrunfolder/.venv/lib/python3.10/site-packages/google/cloud/sql/connector/refresh_utils.py:193> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

From cloud logging I get this more detailed error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/sql/connector/instance.py", line 391, in _refresh_task
    refresh_data = await refresh_task
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/sql/connector/instance.py", line 328, in _perform_refresh
    ephemeral_cert = await ephemeral_task
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/sql/connector/refresh_utils.py", line 193, in _get_ephemeral
    resp = await client_session.post(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://sqladmin.googleapis.com/sql/v1beta4/projects/projectnamehere/instances/instancenamehere:generateEphemeralCert')
```

package list:
```
cloud-sql-python-connector==1.2.4
pg8000==1.29.8
uvicorn==0.22.0
fastapi==0.98.0
```

I'm using an iam service account but authorising using standard user and password for that account, not the iam auth on the cloud sql connector without a password.

FastAPI test code is here if it helps, just using a test table in a test database a the moment. Cloud run is configured to mount secrets as volumes.

```
from fastapi import FastAPI, Depends
from dotenv import load_dotenv
from google.cloud.sql.connector import Connector, IPTypes
from sqlalchemy import create_engine, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

load_dotenv()

db_user = open("/secrets/DBUSERSECRET/DBUSERSECRET", "r").read().strip()
db_name = open("/secrets/DBNAMESECRET/DBNAMESECRET", "r").read().strip()
cloudsql_conninstance = open("/secrets/SQLINSTANCE/SQLINSTANCE", "r").read().strip()
password = open("/secrets/PASSWORD/PASSWORD", "r").read().strip()


# Python Connector database connection function
def getconn():
    with Connector() as connector:
        conn = connector.connect(
            cloudsql_conninstance, # Cloud SQL Instance Connection Name
            "pg8000",
            user=db_user,
            password=password,
            db=db_name,
            ip_type= IPTypes.PRIVATE  # IPTypes.PRIVATE for private IP
        )
        return conn

SQLALCHEMY_DATABASE_URL = "postgresql+pg8000://"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL , creator=getconn, pool_size=5
)

# create SQLAlchemy ORM session
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


app = FastAPI()

# session = SessionLocal()


@app.get("/")
async def root():
    return {"message": "Hello World"}

@app.get("/endpoint01")
def endpoint01( db: SessionLocal = Depends(get_db)):
    import aiohttp.client_exceptions
    # with SessionLocal() as session:
    try:
        sql_result = db.execute(text('SELECT MAX(ID) as max_id FROM test;'))
        for result in sql_result:
            max_id = result[0]
        returnmessage = f'max_id is: {max_id}'
        return({"message":returnmessage}, 200)
    except Exception as e:
        returnmessage = f'exception oh no - type({e}): {e}'
        return({"message":returnmessage}, 500)
```

**Comment by jackwotherspoon** [comment]
@cw-optima-ovo Yes please raise a separate issue and we can get into the details of it. It may be that just need to update the settings of your connection pool.

**Comment by jcz-aml** [comment]
Thanks @jackwotherspoon - just requested the quota uplift.  FWIW, it's gotten **much** worse as we shifted to using IAM db credentials with service accounts; this was recommended by Google as a security measure.

We're tuning the connection pool to extend life of connections (pool_size, pool_recycle) in hope that helps.

**Comment by jcz-aml** [comment]
FYI, @jackwotherspoon made a code change suggestion in the other issue (#772) which resolved this problem for us.
